options:
  logging: CLOUD_LOGGING_ONLY  # Or you can set it to NONE, depending on your needs
  

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-web-app:$COMMIT_SHA', '.']
  
  # Step 2: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-web-app:$COMMIT_SHA']

  # Step 3: Set up kubectl (authentication with GKE)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-cluster-1'  # Replace with your cluster name
      - '--zone'
      - 'us-central1'  # Replace with your cluster's zone
      - '--project'
      - '$PROJECT_ID'

  # Step 4: Deploy to GKE using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'service.yaml'

images:
  - 'gcr.io/$PROJECT_ID/my-web-app:$COMMIT_SHA'
